Pr.3.3.0 p5
hunter-packages/glfw pull request #3
Opened 2018-12-11 09:14 UTC by FelikZ

Pull and resolve conflicts to the latest master in order to fix OSX Mojave issues, see:
https://github.com/glfw/glfw/issues/1333

2018-12-11 09:55 UTC, ruslo requested changes
I've created branch `hunter-3.3.0-f9923e9`, please rebase changes againt it.

2018-12-12 15:20 UTC, FelikZ commented
@ruslo please have a look

2018-12-12 15:40 UTC, ruslo approved these changes

2018-12-12 15:40 UTC, merged

2018-12-12 15:41 UTC, ruslo commented
Released: https://github.com/hunter-packages/glfw/releases/tag/v3.3.0-f9923e9-p0